
-- Problem 2
-- Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
--
-- 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
--
-- By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.


function naive_fib(i)
    if i == 0 then 
        return 0
    elseif i == 1 then
        return 1
    else
        return naive_fib(i - 1) + naive_fib(i - 2)
    end
end

fib_table = {0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233, 377, 610, 987, 1597, 2584, 4181, 6765}

function test_naive_fib()
    for i, result in ipairs(fib_table) do
        arg = i - 1
        result = naive_fib(arg)
        if result == fib_table[i] then
            is_correct = "correct"
        else
            is_correct = "false"
        end
        print("fib(" .. arg .. ") = " .. naive_fib(arg) .. " and is " .. is_correct)
    end
end

memoized = { }
memoized[0] = 0
memoized[1] = 1

function memoized_fib(i)
    local result = memoized[i]
    if result == nil then
        local i_minus_1 = memoized_fib(i - 1)
        local i_minus_2 = memoized_fib(i - 2)
        memoized[i] = i_minus_1 + i_minus_2
        return i_minus_1 + i_minus_2
    else
        -- print("For " .. i .. " returning " .. result)
        return result
    end
end

function test_memoized_fib()
    for i, result in ipairs(fib_table) do
        arg = i - 1
        result = memoized_fib(arg)
        if result == fib_table[i] then
            is_correct = "correct"
        else
            is_correct = "false"
        end
        print("fib(" .. arg .. ") = " .. naive_fib(arg) .. " and is " .. is_correct)
    end
end

print("Testing naive fib")
test_naive_fib()

-- Doesn't finish in 10 nin
-- print("Big number: " .. naive_fib(234242))

print("Testing memoized fib")
test_memoized_fib()
print("Big number: " .. memoized_fib(234242))

i = 0
sum = 0
repeat
    term = memoized_fib(i)
    if term % 2 == 0 then
        sum = sum + term
    end
    i = i + 1
until term > 4000000

print("sum of even terms below 4M = " .. sum)

if sum == 4613732 then
    print("And we got the correct answer!")
else
    print("Which is not the correct answer...")
end